// This file is auto-generated by Lovable. Do not modify it.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import { supabase } from "../supabase/client";
const lovableAuth = createLovableAuth();

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

const isEmbeddedPreview = () => {
  try {
    return window.self !== window.top || window.location.hostname.includes('lovable.app');
  } catch {
    return true;
  }
};

const signInWithSupabaseOAuth = async (provider: "google" | "apple", opts?: SignInOptions) => {
  const embeddedPreview = isEmbeddedPreview();
  const { data, error } = await supabase.auth.signInWithOAuth({
    provider,
    options: {
      redirectTo: opts?.redirect_uri ?? window.location.origin,
      queryParams: opts?.extraParams,
      skipBrowserRedirect: embeddedPreview,
    },
  });

  if (error) return { error };

  if (data.url) {
    if (embeddedPreview) {
      window.open(data.url, '_blank', 'popup,width=520,height=720');
    } else {
      window.location.assign(data.url);
    }
    return { redirected: true };
  }

  return { error: new Error('Could not start Google sign-in') };
};

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: "google" | "apple" | "microsoft", opts?: SignInOptions) => {
      if (provider === 'google') {
        return signInWithSupabaseOAuth(provider, opts);
      }

      const result = await lovableAuth.signInWithOAuth(provider, {
        redirect_uri: opts?.redirect_uri,
        extraParams: {
          ...opts?.extraParams,
        },
      });

      if (result.redirected) {
        return result;
      }

      if (result.error) {
        const message = result.error instanceof Error ? result.error.message : String(result.error);
        if (provider !== 'microsoft' && message.toLowerCase().includes('provider') && message.toLowerCase().includes('not supported')) {
          return signInWithSupabaseOAuth(provider, opts);
        }
        return result;
      }

      try {
        await supabase.auth.setSession(result.tokens);
      } catch (e) {
        return { error: e instanceof Error ? e : new Error(String(e)) };
      }
      return result;
    },
  },
};
